services:
  postgres:
    restart: always
    image: postgres:16-alpine
    container_name: staccato-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
